all:
	@echo -n "Resolvendo dependencias . . ."
	@sleep 0.6
	@cp inter2d.pl inter2d
	@chmod +x inter2d
	@echo -e "\t\t\tOk!"

clean:
	@echo -n "Limpando diretorio . . ."
	@sleep 0.9
	@[ -f inter2d ] && rm -f inter2d
	@echo -e "\t\t\tFeito"

