all:
	@echo -n "Resolvendo dependencias . . ."
	@sleep 0.7
	@echo "\t\t\tOk!"
	@echo -n "Carregando bibliotecas do sistema . . ."
	@sleep 1.1
	@echo "\t\tOk!"
	@cp inter2d.pl inter2d
	@echo -n "Ligando objetos . . ."
	@sleep 0.7
	@chmod +x inter2d
	@echo "\t\t\t\tFeito!"

clean:
	@echo -n "Limpando diretorio . . ."
	@sleep 1.5
	@[ -f inter2d ] && rm -f inter2d
	@echo "\t\t\tFeito"

