all:
	@echo -n "Resolvendo dependencias . . ."
	@sleep 0.7
	@echo "\t\t\tOk!"
	@echo -n "Carregando bibliotecas do sistema . . ."
	@sleep 1.1
	@echo "\t\tOk!"
	@cp molde2d.pl molde2d
	@echo -n "Ligando objetos . . ."
	@sleep 0.7
	@chmod +x molde2d
	@echo "\t\t\t\tFeito!"

clean:
	@echo -n "Limpando diretorio . . ."
	@sleep 1.5
	@[ -f molde2d ] && rm -f molde2d
	@echo "\t\t\tFeito"

