LATEX = pdflatex

all:
	@$(LATEX) apresentacao.tex
	@$(LATEX) apresentacao.tex


clean:
	@rm -f *.pdf\
		   *.aux\
		   *.log\
		   *.nav\
		   *.out\
		   *.snm\
		   *.toc\
		   *.vrb\
		   2>/dev/null
