all:
	@echo -n "Resolvendo dependencias . . ."
	@sleep 0.7
	@echo "\t\t\tOk!"
	@echo -n "Carregando bibliotecas do sistema . . ."
	@sleep 1.1
	@echo "\t\tOk!"
	@cp refinamento.pl refinamento
	@echo -n "Ligando objetos . . ."
	@sleep 0.7
	@chmod +x refinamento
	@echo "\t\t\t\tFeito!"

clean:
	@echo -n "Limpando diretorio . . ."
	@sleep 1.5
	@[ -f refinamento ] && rm -f refinamento
	@echo "\t\t\tFeito"

