# Nome do executavel
EXEC=rotores

all:
	@echo "Criando o executavel"
	@cp maq.pl $(EXEC)
	@chmod +x $(EXEC)
	@echo -e "Feito!\nFormato de execucao:\n\n\t./rotores [-c <arq1>|-d <arq2>] [-s <arq3>] z1..zn\n"


clean:
	@echo "Removendo executavel.."
	@rm -f $(EXEC)
	@echo "Feito"

